### ISSUE TITLE
'em' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by zadjii-msft** [zadjii/keep#1]
This was first reported by @tuyenpm9 in Microsoft/Console#68.

> Non-related question: I got this error when trying to run cmd> reprompt - bin is in PATH
>```
>'em' is not recognized as an internal or external command,
>operable program or batch file.
>```

**Comment by zadjii-msft** [comment]
@tuyenpm9 can you try removing the `@echo off` line from `reprompt.cmd` and paste what it outputs?

**Comment by ghost** [comment]
output:
```
C:\Users\USER>reprompt

C:\Users\USER>rem THis is your seperator character

C:\Users\USER>em    Most fonts don't support the first one, it's a powerline character
'em' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\USER>em    If it's not supported, try another
'em' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\USER>em set _seperator=
'em' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\USER>set _seperator=$g

C:\Users\USER>set GITBRANCH=

C:\Users\USER>FOR /F "tokens=* USEBACKQ" %F IN (`git symbolic-ref --short HEAD 2> NUL`) DO (SET GITBRANCH=%F )

C:\Users\USER>rem set _GITPROMPT=

C:\Users\USER>if "" == "" (set _GITPROMPT=$e[0m )  else (
rem set "_GITPROMPT= $e[48;5;214m[]$e[0m "
 set "_GITPROMPT= $e[43m[]$e[0m "
)

C:\Users\USER>if "" == "" (set "_razPROMPT=" )  else (set "_razPROMPT= [] " )

C:\Users\USER>PROMPT $e[107;30m[$T]$e[97;46m$g$P$e[36;49m$g$e[0m$_$e[0m$e[0m$e[94mUSER$e[0m@$e[32mPC-NAME$e[0m$G
```

**Comment by zadjii** [comment]
whoa, what?

it looks like for whatever reason, the comments on lines [5-9](https://github.com/zadjii/keep/blob/master/bin/reprompt.cmd#L5-L9) aren't working on your clone. 

What happens if you delete those lines?

This is very curious, maybe it has something to do with the powerline character on one of the `_separator` lines, or maybe it's something weird with git checking the file out crlf vs lf mode...

**Comment by ghost** [comment]
@zadjii : I see the problem, in `~/.gitconfig` I forced `autocrlf` to `false` - I work with linux most the time and sometime `^M` at the end of lines caught me. Enable it to `true` and re-clone work. Thanks.

And btw I have this silly question in `wsl`, can you give a look? https://github.com/Microsoft/WSL/issues/ 3531  . I put a space to the number to avoid reference.

**Comment by zadjii** [comment]
Oh, well, that makes sense. Glad to know I wasn't totally insane.

re: your WSL question, I think therealkenc has it right - you don't really need WSL in that scenario, just use vcxsrv or some other windows 10 X server with your VM.
